#!/usr/bin/env bash
#a script that manages manage_my_process

# Function to start the manage_my_process script
start_manage_my_process() {

    ./manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process started"
}

# Function to stop the manage_my_process script
stop_manage_my_process() {

    pid=$(cat /var/run/my_process.pid)
    kill "$pid" && rm -f /var/run/my_process.pid
    echo "manage_my_process stopped"
}

# Function to restart the manage_my_process script
restart_manage_my_process() {
    stop_manage_my_process
    start_manage_my_process
    echo "manage_my_process restarted"
}

# Check arguments and perform respective actions
case "$1" in
    start)
        start_manage_my_process
        ;;
    stop)
        stop_manage_my_process
        ;;
    restart)
        restart_manage_my_process
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac