#!/usr/bin/env bash
# a Bash script that stops 7-highlander process without using kill or killall

# Use pkill to stop the '7-highlander' process
pkill -f "7-highlander"

# # Check if the process is still running after attempting to stop it
# if pgrep -f "7-highlander" > /dev/null
# then
#     # If the process still running # Forcefully kill the process
#     pkill -9 -f "7-highlander"
# fi